export const RECIPES_REQUEST = 'RECIPES_REQUEST';
export const RECIPES_SUCCESS = 'RECIPES_SUCCESS';
export const RECIPES_ERROR = 'RECIPES_ERROR';

export const DELETE_RECIPE_REQUEST = 'DELETE_RECIPE_REQUEST';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const DELETE_RECIPE_ERROR = 'DELETE_RECIPE_ERROR';

export const POST_RECIPE_REQUEST = 'POST_RECIPE_REQUEST';
export const POST_RECIPE_SUCCESS = 'POST_RECIPE_SUCCESS';
export const POST_RECIPE_ERROR = 'POST_RECIPE_ERROR';
