export const CATEGORIES_REQUEST = 'CATEGORY_REQUEST';
export const CATEGORIES_SUCCESS = 'CATEGORY_SUCCESS';
export const CATEGORIES_ERROR = 'CATEGORY_ERROR';

export const DELETE_CATEGORY_REQUEST = 'DELETE_CATEGORY_REQUEST';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';

export const POST_CATEGORY_REQUEST = 'POST_CATEGORY_REQUEST';
export const POST_CATEGORY_SUCCESS = 'POST_CATEGORY_SUCCESS';
export const POST_CATEGORY_ERROR = 'POST_CATEGORY_ERROR';

export const PUT_CATEGORY_REQUEST = 'PUT_CATEGORY_REQUEST';
export const PUT_CATEGORY_SUCCESS = 'PUT_CATEGORY_SUCCESS';
export const PUT_CATEGORY_ERROR = 'PUT_CATEGORY_ERROR';
